name = "first-worker"
main = "src/index.ts"
compatibility_date = "2022-07-10"

[[kv_namespaces]]
binding = "kv_first"
id = "ccd0a04a08b34ba29e78d47fd733779f"
preview_id = "6360586c2c304fb2818c982d02bed898"
