name: Deploy

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
